### ISSUE TITLE
combined barplot missing

### ISSUE THREAD

**Issue by marade** [PombertLab/SYNY#5]
Greetings. The SYNY home page shows a combined barplot output:

https://github.com/PombertLab/SYNY?tab=readme-ov-file#barplots

But when I run SYNY and I look in BARPLOTS/PNG or BARPLOTS/SVG directories I only see individual comparisons and no combined image. Is there a hidden flag to activate that?

**Comment by Pombert-JF** [comment]
Not at the moment. Concatenation into a single barplot would likely require a rewrite of the backend unless we "cheat" by concatenating the PAF files first. Then `paf_to_barplot.py` should work without a fuss on the concatenated PAF files. Might be the easiest way forward. Color coding could be problematic however.  I can implement a color coding by clusters option (like for the Circos plots) but I'm not sure how useful that would be. 

I'll look into it tomorrow. You can try it yourself by concatenating the PAF files with the same reference together, e.g. `cat *_vs_ref.mmap.paf > ref_concatenated.paf`, then running  ` paf_to_barplot.py --paf ref_concatenated.paf --fasta *.fasta --outdir TEST ` (or something like that) on the concatenated PAF file.

Otherwise, you could always concatenate the barplots you want from the SVG outputs with Adobe Illustrator or Inkscape (https://inkscape.org/).

**Comment by marade** [comment]
Thanks, that's helpful. I'll let you do the updates and test again, but it sounds like I'll be able to make it work one way or another.

**Comment by Pombert-JF** [comment]
As discussed, I pushed a new version that can produces concatenated barplots. Just need to invoke `--bpmode cat` (or `--bpmode all`). The default is set to `--bpmode pair` since most people will want the pairwise plots.

Example of a concatenated barplot produced from small eukaryote genomes (4 queries x 1 reference):
![all_vs_Ec50602 gap_0 barplot 19 2x10 8 Spectral](https://github.com/PombertLab/SYNY/assets/6370915/438501b6-8ebf-4162-9b28-ced6efd67745)

I also implemented a `--bclusters` option to color clusters by alternating colors in the barplots. The colors are not related within or between contigs, they are just used to highlight collinear chunks. If you want to use that, you'll likely want to use a qualitative palette instead of the default sequential one ([possible palettes](https://github.com/PombertLab/SYNY/blob/main/Images/python_color_palettes.png)). The image below was generated with `--bclusters` and `--palette Paired`

![Ec50602_vs_OpFIF10 mmap barplot 19 2x10 8 clus](https://github.com/PombertLab/SYNY/assets/6370915/ba997db4-fd13-4195-91a8-daa098ddfc47)

Hope these additions help. Will close this issue as resolved but let me know if you encounter any issue.

**Comment by marade** [comment]
Thanks, this works well, very much as anticipated. One issue I am noticing is that for sequences that are 100% identical, there is a small gap at the end of the plots. Are you seeing that too?

![all_vs_Xj1 gap_0 barplot 19 2x10 8 blue](https://github.com/PombertLab/SYNY/assets/12517405/7121287d-3305-4b4a-ab0e-4589d8aee353)

**Comment by Pombert-JF** [comment]
No, could very well be a bug. Can you send me those files file so that I can debug it?

**Comment by marade** [comment]
Sure, sent via e-mail...

**Comment by Pombert-JF** [comment]
Yup bug. Forgot to add a `line.strip()` to remove newlines, so it was adding them as extra length. Pushed the fix to github.

**Comment by marade** [comment]
Yes, looks good. Thanks again.
