### ISSUE TITLE
Too many links for circos production

### ISSUE THREAD

**Issue by Victaphanta** [PombertLab/SYNY#9]
Hi, Thank you for the wonderful pipeline.
I am comparing genomes of two closely related species of marsupials.  Both genome are assembled to chromosome level (n=7).  All is running fine.  Most figures are produced, the exception is the circos plot of the mninmap alignment results.  Essentially it resulted in too many link, surpassing the limit of 75000 links.

*** CIRCOS ERROR ***

      cwd:
      /media/strangesta/DATA2/GENOMES/ANNOTATION/Dasyurus_hallucatus_20240522/SYNY

      command: /home/strangesta/circos-0.69-9/bin//circos -conf
      ...Dasyurus_hallucatus_10X_01_style3pseudohapfull_HiC_vs_GCA_020854095.mmap.normal.conf
      -outputdir
      .../SYNY/OUT/DH_DV/PLOTS/CIRCOS/Pairwise
      -outputfile
      Dasyurus_hallucatus_10X_01_style3pseudohapfull_HiC_vs_GCA_020854095.mmap.normal.png
      -silent

  You have asked to draw [744206] links from file...
  but the maximum is currently set at [75000]. To increase this number change
  max_links in etc/housekeeping.conf. Keep in mind that drawing that many links
  may create an image that is too busy and uninterpretable.

I set this run to ASM5.
Wondering how best to move forward with this, perhaps to filter the the minmap results for very high quality hits only.

Any suggestions.  
Many thanks.

**Comment by Pombert-JF** [comment]
You can set the max number of links in the circos plots when running SYNY with the `--max_links` command line switch. e.g. `run_syny.pl --max_links 800000`.  You don't need to edit the circos etc/housekeeping.conf file; its default settings are overruled by the `--max_ticks`, `--max_ideograms`, `--max_links` and `--max_points_per_track` command line switches.

Alternatively, you could also edit your existing circos .conf file(s) (in the `PLOTS/CIRCOS_DATA/` subdirectory) to change the corresponding line: `max_links            = 75000`. Then, rerun circos on it: _e.g._ `circos -conf filename.conf`

With that many links though, the resulting figure might be a bit too dense. You could try running the mapping step with mashmap instead of minimap. If the result is similar and you want something less dense, then yes filtering the PAF files would be the way to go I think.

Hope this helps,
JF

**Comment by Victaphanta** [comment]
Thanks JF, will try this and see how it looks.
